name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
      with:
        flutter-version: '1.15.3'
        channel: 'dev'
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
